### ISSUE TITLE
Error regarding search config

### ISSUE THREAD

**Issue by pedrorolando** [MattieBelt/mattie-strapi-bundle#143]
I get this error even though I have setup my config exactly as your docs recommend, included my API keys, etc. and also after clearing node_modules, lock files, etc.

`Error regarding search config: Search plugin ConfigValidationError: provider is a required field`

Is this just me?

**Comment by pedrorolando** [comment]
This was my fault I'm an idiot sorry closing now

**Comment by sauldeleon** [comment]
hey @pedrorolando it seems I am as idiot as you were, because Im having the same issue and I cant figure out what Im doing wrong...

Could you tell me what was your fix?

thanks!

Edit: Guess what. I am idiot as well.

For future idiots, remember not to move the dist files before starting the application.
